# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-06 17:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pixeldb', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='Genre',
        ),
        migrations.AddField(
            model_name='game',
            name='Genre',
            field=models.ManyToManyField(to='pixeldb.Genre'),
        ),
    ]
