# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-06 19:18
from __future__ import unicode_literals

from django.db import migrations, models
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('pixeldb', '0002_auto_20171006_1939'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='text',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='blog',
            name='slug',
            field=django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from='headline'),
        ),
    ]
